import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, describe, expect, it, vi } from "vitest";
import { httpClient } from "../../../../lib/httpClient";
import { AdminPackagesPage } from "./AdminPackagesPage";
const item = { id: 1, name: "Starter 30", durationDays: 30, price: 500000, description: "Thirty days.", isActive: true };
function renderPage() { const client = new QueryClient({ defaultOptions: { queries: { retry: false } } }); return render(<QueryClientProvider client={client}><AdminPackagesPage /></QueryClientProvider>); }
afterEach(() => vi.restoreAllMocks());
describe("AdminPackagesPage", () => { it("renders the admin package table", async () => { vi.spyOn(httpClient, "get").mockResolvedValue({ status: 200, data: { success: true, message: "ok", data: [item] } }); renderPage(); expect(await screen.findByText("Starter 30")).toBeInTheDocument(); expect(screen.getByText("ACTIVE")).toBeInTheDocument(); }); it("creates a package and prevents duplicate submit while pending", async () => { vi.spyOn(httpClient, "get").mockResolvedValue({ status: 200, data: { success: true, message: "ok", data: [] } }); vi.spyOn(httpClient, "post").mockResolvedValue({ status: 201, data: { success: true, message: "created", data: item } }); const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Create package" })); await user.type(screen.getByLabelText("Package name *"), "Starter 30"); await user.click(screen.getAllByRole("button", { name: "Create package" })[1]); expect(await screen.findByRole("status")).toHaveTextContent("created"); expect(httpClient.post).toHaveBeenCalledTimes(1); }); it("soft deactivates after confirmation", async () => { vi.spyOn(httpClient, "get").mockResolvedValue({ status: 200, data: { success: true, message: "ok", data: [item] } }); vi.spyOn(window, "confirm").mockReturnValue(true); vi.spyOn(httpClient, "delete").mockResolvedValue({ status: 200, data: { success: true, message: "deactivated", data: { ...item, isActive: false } } }); const user = userEvent.setup(); renderPage(); await user.click(await screen.findByRole("button", { name: "Deactivate" })); expect(await screen.findByRole("status")).toHaveTextContent("deactivated"); expect(httpClient.delete).toHaveBeenCalledWith("/admin/packages/1"); }); });
